M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-08-29T11:43:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-29T11:43:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
%
G90
G05
T1
X222.0Y-92.0
X222.0Y-148.0
X246.9Y-92.0
X246.9Y-148.0
M30
