@startuml
title Hardware Block Diagram: Gateway

' --- Style ---
skinparam componentStyle rectangle
skinparam monochrome true

' --- Components ---
node "Power Supply" {
    [DC-DC] as PWR << 5V to 3.3V Regulator >>
}

node "Processing" {
    [MCU] as CTRL << STM8L151 >>
    [FeRAM] as FERM << 8 KB >>
}

node "RF Front-End, 433 MHz" {
    [RF Transceiver] as RF_CHIP << CC1101 >>
    [Balun] as BAL
    [Pi-Match] as PI_NET
    [Antenna] as ANT << 50 ohm >>
}

node "Peripherals" {
    [L Reed Switch] as REEDL
    [R Reed Switch] as REEDR
    [Push Button] as BTN
    [LED B] as LED_B
    [LED R] as LED_R
    [LED Y] as LED_Y
    [BUZZER] as BZR
}

' --- Connections ---

' Power Distribution (Parallel connection from Power node)
PWR -[bold]-> CTRL : VCC
PWR -[bold]-> RF_CHIP : VCC
PWR -[bold]-> FERM : VCC

' Logic/Signals
CTRL <-left-> FERM : I2C
CTRL <-> RF_CHIP : SPI / GDO
REEDR -up- REEDL
REEDL -up-> CTRL : GPIO
BTN -up-> CTRL : GPIO
LED_B <-up- CTRL : GPIO
LED_R <-up- CTRL : GPIO
LED_Y <-up- CTRL : GPIO
BZR <-up- CTRL : GPIO

' RF Path
RF_CHIP -right-> BAL
BAL -right-> PI_NET
PI_NET -right-> ANT

@enduml