@startuml Wireless Sensor
skinparam componentStyle rectangle
skinparam defaultFontName Monospace
skinparam linetype ortho
skinparam nodesep 150
skinparam ranksep 50


node "Sensor" {
[BAT] as BAT
[Reed Switch] as REED
[MCU] as MCU
[Voltage Supervisor] as VS
[OOK TX 868 MHz] as TX
[Balun] as BALUN
[Pi-Matching] as PI
[Antenna] as ANT
}


BAT -down- MCU: Vdd
BAT -down- VS: Vdd
BAT -down- TX: Vdd

REED -right---> MCU : open/close edge
VS -right-> MCU: batt_low flag

MCU -right-> TX : encoded bursts ×3
TX -right-> BALUN: differential OOK RF
BALUN -right-> PI: 50ohms
PI -right-> ANT: RF radiation
@enduml